//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamageVision.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DamageVision.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭程序.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏结束时关闭程序.
        /// </summary>
        internal static string ExitOnGameExit {
            get {
                return ResourceManager.GetString("ExitOnGameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拖拽可移动位置.
        /// </summary>
        internal static string Prompt1 {
            get {
                return ResourceManager.GetString("Prompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滚轮可调整高度.
        /// </summary>
        internal static string Prompt2 {
            get {
                return ResourceManager.GetString("Prompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滚轮+Shift/Alt/Ctrl.
        /// </summary>
        internal static string Prompt3 {
            get {
                return ResourceManager.GetString("Prompt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可调整字号/透明度/宽度.
        /// </summary>
        internal static string Prompt4 {
            get {
                return ResourceManager.GetString("Prompt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务后显示伤害值.
        /// </summary>
        internal static string ShowDamageAfterQuest {
            get {
                return ResourceManager.GetString("ShowDamageAfterQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务中显示伤害值.
        /// </summary>
        internal static string ShowDamageInQuest {
            get {
                return ResourceManager.GetString("ShowDamageInQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示DPS.
        /// </summary>
        internal static string ShowDps {
            get {
                return ResourceManager.GetString("ShowDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务后显示百分比.
        /// </summary>
        internal static string ShowPercentageAfterQuest {
            get {
                return ResourceManager.GetString("ShowPercentageAfterQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务中显示百分比.
        /// </summary>
        internal static string ShowPercentageInQuest {
            get {
                return ResourceManager.GetString("ShowPercentageInQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Vision.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
